apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitsynergy-app-deployment
spec:
  selector:
    matchLabels:
      app: fitsynergy-app
  replicas: 2
  template:
    metadata:
      labels:
        app: fitsynergy-app
    spec:
      containers:
        - name: fitsynergy-app
          image: misharyduk/fitsynergy-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: fitsynergy-app-service
spec:
  selector:
    app: fitsynergy-app
  ports:
    - protocol: "TCP"
      port: 9000
      targetPort: 9000
  type: NodePort